In [2]:
#password strength checker
def is_strong_password(password):
    if  len(password)<8:
        return False
    if not any(char.isdigit() for char in password):
         return False
    if not any(char.islower() for char in password):
        return False
    if not any(char.isupper() for char in password):
        return False
    return True
print(is_strong_password("hdhfb"))  

False


In [3]:
def calculate_total_cost(cart):
    total_cost = 0
    for item in cart:
        total_cost += item['price'] * item['quantity']
    
    return total_cost

cart = [
    {'name': 'apple', 'price': 30, 'quantity': 3},
    {'name': 'banana', 'price': 45, 'quantity': 6}
]

print(calculate_total_cost(cart))

360


In [4]:
addition=lambda  a,b:a+b
print(addition(5,8))

13


In [5]:
def linear_search(arr,taraget):
    size=len(arr)
    for index in range(0,size):
        if(arr[index]==taraget):
            return index
    return -1
my_list=[1,2,3,4,5,6]
taraget=3
result=linear_search(my_list,taraget)
print(result)
  

2


In [6]:

import numpy as np
avarge=np.array([1,2,3,4,5,6,7])
av=np.mean(avarge)
print(av)




4.0


import numpy as np

In [7]:
import numpy as np
zeros_array=np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [8]:
import numpy as np
ones_arr=np.ones((4,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
import numpy as np
full_arr=np.full((3,6),4)
print(full_arr)

[[4 4 4 4 4 4]
 [4 4 4 4 4 4]
 [4 4 4 4 4 4]]


In [10]:
import numpy as np
arr=np.arange(1,20,3)
print(arr)

[ 1  4  7 10 13 16 19]


In [11]:
import numpy as np
identity_matirx=np.eye(5)
print(identity_matirx)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
#array prpperties and opearation
import numpy as np
arr_2d=np.array([[1,2,3,4],
                [6,7,8,9]])
print(arr_2d)
arr_2d.shape

[[1 2 3 4]
 [6 7 8 9]]


(2, 4)

In [13]:
import numpy as np
arr_1=np.array([1,2,3])
arr_2=np.array([[1,2,3],[5,6,7]])
arr_3=np.array([[[1,2,3],[2,3,4],[4,5,6]]])
print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)

1
2
3


In [14]:
import numpy as np
arr=np.array([1.2,3.4,5.6])
int_Arr=arr.astype(int)

In [15]:
import numpy as np
arr_1=np.array([1,2,3])
print(arr_1*5)

[ 5 10 15]


In [16]:
np.sum(arr_1)
np.mean(arr_1)

np.float64(2.0)

In [17]:
#indexing and slicing

In [18]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr[:4])
print(arr[::2])
print(arr[:4:2])
print(arr[::2])
print(arr[[1,2,3]])


[1 2 3 4 5]
[1 2 3 4]
[1 3 5]
[1 3]
[1 3 5]
[2 3 4]


In [19]:
#reshaping and manipulating arrays
import numpy as np



In [20]:
import numpy as np
arr=np.array([10,20,20,34,45,67])
print(arr[arr>23])

[34 45 67]


In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
resahped=arr.reshape(2,3)

In [22]:
# array manipulating
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=np.insert(arr,3,45)
print(new_arr)


[ 1  2  3 45  4  5  6]


In [23]:
import numpy as np
arr1=np.array([[1,2],[34,56]])
arr1=np.insert(arr1,1,[3,4],axis=0)
arr1=np.insert(arr1,1,[3,4],axis=None)

arr1
arr1

array([ 1,  3,  4,  2,  3,  4, 34, 56])

In [24]:
import numpy as np
ar2=np.array([1,2])
new_arr1=np.append(ar2,[4,5])
print(new_arr1)

[1 2 4 5]


In [25]:
import numpy as np
arrr2=np.array([[1,2],[3,4]])
newarr=np.insert(arrr2,2,(5,6))
print(newarr)

[1 2 5 6 3 4]


In [26]:

import numpy as np
arrr2 = np.array([[1,2],[3,4]])
newarr = np.insert(arrr2, 2, (8,6), axis=0)
print(newarr)


[[1 2]
 [3 4]
 [8 6]]


In [27]:
import numpy as np
array_1=np.array([1,2])
array_2=np.array([3,4])
new_array1=np.concatenate((array_1,array_2))
print(new_array1)

[1 2 3 4]


In [28]:
import numpy as np
array_1=np.array([1,2])
array_2=np.array([3,4])
new_array1=np.concatenate((array_1,array_2))
print(new_array1)

[1 2 3 4]


In [29]:
import pandas as pd


ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd
df={
    'name':'vasu'
}

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd
data={
    'name':['vasu','tanuja','ram','mananjay','pawan'],
    'age':[24,28,None,None,34],
    'slary':[25000,30000,None,45000,None]
}

ModuleNotFoundError: No module named 'pandas'